spring.application.name=backend

# SQLite Database Configuration
# spring.datasource.url=jdbc:sqlite:./data/glpi_kanban.db
spring.datasource.url=jdbc:sqlite:glpi_kanban.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher